Repository muesli/deckmaster, pull requests merged in 2021-06, with the labels that each got.

#22 Background-Wallpaper
  config.go
  deck.go
  go.mod
  go.sum
  main.go
  widget.go
  widget_button.go
  widget_recent_window.go
  widget_time.go
  widget_top.go
Labels: enhancement

#25 Add widget documentation
  README.md
Labels: documentation

#26 Add known configuration values to README
  README.md
Labels: documentation

#29 Add keycodes file and replace keycodes accordingly
  deck.go
  keycodes.go
Labels: enhancement

#27 Small changes in README
  README.md
Labels: documentation

#31 Add per widget update intervals with possilbe configuration in deck files
  config.go
  deck.go
  main.go
  widget.go
  widget_button.go
  widget_recent_window.go
Labels: enhancement

#32 Allow for non-string config map values
  config.go
  deck.go
  decks/main.deck
  go.sum
  widget.go
  widget_button.go
  widget_recent_window.go
  widget_time.go
  widget_top.go
Labels: enhancement

#30 Expand tilde to home-dir for decks and images
  deck.go
  go.mod
  go.sum
  images.go
Labels: enhancement

#33 Command widget
  README.md
  widget.go
  widget_command.go
Labels: enhancement

#41 Update README to describe the functionality of theme
  README.md
Labels: documentation

#39 Expand tilde for exec commands as well
  deck.go
Labels: core, enhancement

#42 Fix exec path expand and small README addition
  README.md
  main.go
Labels: bug
