Repository muesli/deckmaster, pull requests merged in 2022-02, with the labels that each got.

#68 Add sleep timeout flag
  README.md
  go.mod
  go.sum
  main.go
Labels: enhancement

#63 Document deck switching
  README.md
Labels: documentation

#70 Add verbose flag and clean up printing to stdout/stderr
  deck.go
  desktop_unix.go
  layouts.go
  main.go
  widget_recent_window.go
  widget_weather.go
  window.go
Labels: enhancement

#71 Update README badges
  README.md
Labels: documentation

#59 Added brightness control actions.
  README.md
  config.go
  deck.go
  decks/main.deck
Labels: enhancement

#72 Add device sleep action
  README.md
  deck.go
  decks/main.deck
  go.mod
  go.sum
Labels: enhancement

#76 Add version flag
  main.go
Labels: enhancement

#83 fix: weather data refreshing shouldn't block rendering
  widget_weather.go
Labels: bug

#90 ci: update golangci-lint-action to v3
  .github/workflows/lint-soft.yml
  .github/workflows/lint.yml
Labels: dependencies
